name: flutter_map_animated_polyline
description: Animate polylines in flutter_map
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.2.1
  flutter_map_tappable_polyline: ^6.0.0
  latlong2: ^0.9.1
  maps_toolkit: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
