name: flutter_map_animated_polyline
description: Animate polylines with smooth transitions in flutter_map
version: 0.0.1+1
repository: https://github.com/sunenvidiado-nx/flutter-map-animated-polyline

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  maps_toolkit: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
