name: Tests

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - "v*"
  workflow_dispatch:

jobs:
  verification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if test directory exists
        id: check_tests
        run: |
          if [ -d "test" ]; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.0 # Must be the same with the one in pubspec.yaml

      - name: Download dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-pub

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Run tests with coverage
        if: steps.check_tests.outputs.has_tests == 'true'
        run: flutter test --test-randomize-ordering-seed random
